name: Auto Indexing

on:
  push:
    branches:
      - main
      - restore-12f3c10

jobs:
  bing_auto_index:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # 버전을 v4로 수정

    - name: Run indexing script
      run: |
        # 여기에 색인을 위한 스크립트나 명령어를 작성합니다.

# 아래 빙 API 호출 부분은 주석 처리합니다.
#  bing_index:
#    runs-on: ubuntu-latest
#    steps:
#    - name: Checkout code
#      uses: actions/checkout@v4  # 버전을 v4로 수정
#
#    - name: Bing Auto Index
#      run: |
#        curl -H "Ocp-Apim-Subscription-Key: ${{ secrets.BING_API_KEY }}" -X POST "https://api.bing.microsoft.com/v7.0/spy/submit?siteUrl=https://moneydory.github.io/&urlList=https://moneydory.github.io/new-post/"
